version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
    assignees:
      - nikcani
    groups:
      docker:
        patterns:
          - "*"
